# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aliexpress', '0002_auto_20170726_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryresult',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='aliexpress.Query', verbose_name='查询关键字'),
        ),
    ]
