# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliexpress', '0003_auto_20170727_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryresult',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='订单量'),
        ),
    ]
