# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliexpress', '0004_auto_20170728_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queryresult',
            old_name='order',
            new_name='orders',
        ),
        migrations.RemoveField(
            model_name='queryresult',
            name='page_number',
        ),
        migrations.AddField(
            model_name='queryresult',
            name='Credit_points',
            field=models.FloatField(blank=True, default=100.0, null=True, verbose_name='店铺信誉分'),
        ),
        migrations.AddField(
            model_name='queryresult',
            name='comments',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='queryresult',
            name='favorate_rate',
            field=models.FloatField(blank=True, default=100.0, null=True, verbose_name='商品好评率'),
        ),
        migrations.AddField(
            model_name='queryresult',
            name='img_url',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='图片链接'),
        ),
        migrations.AddField(
            model_name='queryresult',
            name='product_url',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='商品链接'),
        ),
        migrations.AddField(
            model_name='queryresult',
            name='rating',
            field=models.FloatField(blank=True, default=100.0, null=True, verbose_name='商品评分'),
        ),
        migrations.AlterField(
            model_name='queryresult',
            name='rank',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='排名'),
        ),
    ]
