# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliexpress', '0005_auto_20170730_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queryresult',
            old_name='Credit_points',
            new_name='credit_points',
        ),
        migrations.AddField(
            model_name='queryresult',
            name='page',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='页码'),
        ),
    ]
