# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliexpress', '0006_auto_20170730_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryresult',
            name='product_code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='产品编号'),
        ),
    ]
