# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliexpress', '0007_queryresult_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryresult',
            name='overall_rank',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='整体排名'),
        ),
    ]
