# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 00:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aliexpress', '0009_query_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=64, verbose_name='查询关键字')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='查询时间')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aliexpress.Country', verbose_name='查询站点')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='查询用户')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedQueryResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(blank=True, max_length=128, null=True, verbose_name='相关词')),
                ('count', models.IntegerField(blank=True, default=0, null=True, verbose_name='数量')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='aliexpress.RelatedQuery', verbose_name='查询关键字')),
            ],
        ),
    ]
