# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliexpress', '0010_relatedquery_relatedqueryresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedqueryresult',
            name='count',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='数量'),
        ),
    ]
